name: Build And Deploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.deploy_key }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: dist
